[project]
name = "domain-scanner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.7.1",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.40",
]
