"""Add schedule table

Revision ID: 38c217c478be
Revises: 557033280e72
Create Date: 2025-05-04 16:58:30.579260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c217c478be'
down_revision: Union[str, None] = '557033280e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_scan_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule_type', sa.Enum('date', 'interval', 'cron', name='scheduletype'), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('cron_second', sa.String(), nullable=True),
    sa.Column('cron_minute', sa.String(), nullable=True),
    sa.Column('cron_hour', sa.String(), nullable=True),
    sa.Column('cron_day', sa.String(), nullable=True),
    sa.Column('cron_month', sa.String(), nullable=True),
    sa.Column('cron_day_of_week', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scan_schedules')
    # ### end Alembic commands ###
