"""Add schedule scan id

Revision ID: 81a26baff323
Revises: 38c217c478be
Create Date: 2025-05-04 19:38:28.508597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81a26baff323'
down_revision: Union[str, None] = '38c217c478be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_scan_schedules', sa.Column('user_scan_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_scan_schedules', 'user_scan_id')
    # ### end Alembic commands ###
