"""add_schedule_name

Revision ID: e920ecd6a4a0
Revises: 81a26baff323
Create Date: 2025-05-05 21:47:04.634060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e920ecd6a4a0'
down_revision: Union[str, None] = '81a26baff323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_scan_schedules', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_scan_schedules', 'name')
    # ### end Alembic commands ###
